#!/usr/bin/env bash
# Control the Lion service.
# Written by Tiger Sachse.

COG_DIR="cogs"
DOCS_DIR="docs"
INSTALL_DIR="/opt"
PACKAGE_NAME="lion"
DISABLED_DIR="disabled"
TOKEN_FILE="discord.token"
VERSION_FILE="VERSION.txt"
SERVICE_FILE="lion.service"

# Add a token for the service.
add_token() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi
    echo "Adding token..."
    echo $1 > "$INSTALL_DIR/$PACKAGE_NAME/$TOKEN_FILE"
}

# Start the service.
start_service() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi
    echo "Starting Lion..."
    systemctl start $SERVICE_FILE
}

# Kill the service.
kill_service() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi
    echo "Killing Lion..."
    systemctl stop $SERVICE_FILE
}

# Restart the service.
restart_service() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi
    echo "Restarting Lion..."
    systemctl restart $SERVICE_FILE
}

# Enable the service.
enable_service() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi
    echo "Enabling Lion..."
    systemctl enable $SERVICE_FILE
}

# Disable the service.
disable_service() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi
    echo "Disabling Lion..."
    systemctl disable $SERVICE_FILE
}

# Get the status of the service.
get_service_status() {
    echo "Getting Lion's status..."
    systemctl status $SERVICE_FILE
}

# Show this service's version and related information.
show_version() {
    cat "$INSTALL_DIR/$PACKAGE_NAME/$DOCS_DIR/$VERSION_FILE"
}

# Show the most recent log entries by this service.
show_log() {
    journalctl -b -u $SERVICE_FILE
}

# Show a simple help message.
show_help() {
    printf "Command syntax:\n    $ lion [--flag] <parameter>\n\n"
    echo "Check out https://github.com/tgsachse/lion for all available flags."
}

# Enable installed cogs.
enable_cogs() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi

    ENABLED_COG=false
    for COG in "$@"; do
        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR/$COG"
        if [ -d $COG_PATH ]; then
            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"
            echo "Enabled cog: $COG"
            ENABLED_COG=true
        else
            echo "Cog not found: $COG"
        fi
    done

    if [ "$ENABLED_COG" = true ]; then
        printf "\nYou should restart the bot for changes to take effect.\n"
    fi
}

# Disable unwanted cogs.
disable_cogs() {
    if [[ $EUID -ne 0 ]]; then
        echo "You must run this function as a root user (or with sudo)."
        exit 1
    fi

    DISABLED_COG=false
    for COG in "$@"; do
        COG_PATH="$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR/$COG"
        if [ -d $COG_PATH ]; then
            mv $COG_PATH "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"
            echo "Disabled cog: $COG"
            DISABLED_COG=true
        else
            echo "Cog not found: $COG"
        fi
    done

    if [ "$DISABLED_COG" = true ]; then
        printf "\nYou should restart the bot for changes to take effect.\n"
    fi
}

# List all enabled cogs.
list_cogs() {
    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$COG_DIR)" ]; then
        echo "Enabled cogs:"
        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$COG_DIR"/*; do
            COG=$(basename "$COG_PATH")
            echo "  $COG"
        done
    else
        echo "No enabled cogs!"
    fi
}

# List all disabled cogs.
list_disabled_cogs() {
    if [ "$(ls -A $INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR)" ]; then
        echo "Disabled cogs:"
        for COG_PATH in "$INSTALL_DIR/$PACKAGE_NAME/$DISABLED_DIR"/*; do
            COG=$(basename "$COG_PATH")
            echo "  $COG"
        done
    else
        echo "No disabled cogs!"
    fi
}

# Main entry point to the script.
case $1 in
    --token)
        add_token $2
        ;;
    -s|--start)
        start_service
        ;;
    -k|--kill|--stop)
        kill_service
        ;;
    -r|--restart)
        restart_service
        ;;
    -e|--enable)
        enable_service
        ;;
    -d|--disable)
        disable_service
        ;;
    --status)
        get_service_status
        ;;
    --version)
        show_version
        ;;
    --log)
        show_log
        ;;
    --enable-cogs)
        enable_cogs "${@:2}"
        ;;
    --disable-cogs)
        disable_cogs "${@:2}"
        ;;
    --list-cogs)
        list_cogs
        ;;
    --list-disabled-cogs)
        list_disabled_cogs
        ;;
    -h|--help|*)
        show_help
        ;;
esac
